### ISSUE TITLE
Django 1.3 tests don't pass with current master

### ISSUE THREAD

**Issue by diox** [fwenzel/django-sha2#15]
I have no idea why yet, but:

<pre>
[TOX] /home/mat/work/django-sha2$ .tox/py27-13/bin/python setup.py test13
running test13
nosetests --verbosity 1
Creating test database for alias 'default'...
......E
======================================================================
ERROR: Test various password hashes.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mat/work/django-sha2/test/django13/../django13/tests/test_sha2.py", line 45, in test_hexdigest
    eq_(get_hexdigest(algo, self.SALT, pw), hashed)
  File "/home/mat/work/django-sha2/.tox/py27-13/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 35, in get_hexdigest
    raise ValueError("Got unknown password algorithm type in password.")
ValueError: Got unknown password algorithm type in password.

----------------------------------------------------------------------
Ran 7 tests in 8.983s

FAILED (errors=1)
Destroying test database for alias 'default'...
[TOX] ERROR: InvocationError: '.tox/py27-13/bin/python setup.py test13'
</pre>

**Comment by diox** [comment]
Will be fixed by merging #16
